# Generated by Django 3.2.13 on 2023-03-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_info',
            field=models.CharField(default='', max_length=256),
        ),
    ]
