# Generated by Django 3.2.13 on 2023-03-30 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_short_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_info',
        ),
    ]
