# Generated by Django 4.1.6 on 2023-02-20 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_rename_houses_house'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
    ]
