# Generated by Django 4.1.7 on 2023-03-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='short_info',
            field=models.CharField(default='краткое описание', max_length=250, verbose_name='Коротко'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='lessons/photos', verbose_name='фото'),
        ),
    ]
