# Generated by Django 4.1.7 on 2023-03-31 08:44

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('lessons', '0002_lessons_short_info_alter_lessons_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
