# Generated by Django 4.1.7 on 2023-04-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lessons_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='stripe_product_price_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
