# Generated by Django 4.1.7 on 2023-04-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_lessons_stripe_product_price_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderingLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lesson', models.CharField(max_length=25, verbose_name='id урока')),
                ('user', models.CharField(max_length=25, verbose_name='user')),
            ],
        ),
    ]
