# Generated by Django 4.1.7 on 2023-04-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_orderinglessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinglessons',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='lessons/photos', verbose_name='фото'),
        ),
        migrations.AddField(
            model_name='orderinglessons',
            name='lesson_description',
            field=models.TextField(blank=True, null=True, verbose_name='info'),
        ),
        migrations.AddField(
            model_name='orderinglessons',
            name='lesson_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='lesson name'),
        ),
        migrations.AddField(
            model_name='orderinglessons',
            name='video_link',
            field=models.CharField(default='', max_length=256, verbose_name='video_link'),
        ),
    ]
