# Generated by Django 4.1.7 on 2023-04-04 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_orderinglessons_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='ordering_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.orderinglessons'),
        ),
    ]
