# Generated by Django 4.1.7 on 2023-04-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_pay_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinglessons',
            name='id_lesson_int',
            field=models.IntegerField(blank=True, null=True, verbose_name='id unt'),
        ),
    ]
