# Generated by Django 4.1.7 on 2023-04-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_orderinglessons_id_lesson_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='video_link',
            field=models.CharField(default='--', max_length=250, verbose_name='Видео ссылка'),
        ),
    ]
