# Generated by Django 4.1.7 on 2023-04-06 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_lessons_create_at_lessons_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='ordering_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.orderinglessons'),
        ),
    ]
