# Generated by Django 4.1.7 on 2023-04-06 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_alter_lessons_ordering_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='file',
            field=models.FileField(blank=True, upload_to='video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
